version: "0.2"
ignorePaths:
  - LICENSE
dictionaryDefinitions: []
dictionaries: []
words:
  - deepsource
  - devbloom
  - pfouilloux
  - preinstallation
  - trunkio
  - underserved
ignoreWords: []
import: []
